# Generated by Django 3.2 on 2021-04-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.location')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantName', models.CharField(choices=[('styleZone', 'Style Zone')], default='styleZone', max_length=20)),
                ('productType', models.CharField(choices=[('fragile', 'Fragile'), ('liquid', 'Liquid')], default='liquid', max_length=23)),
                ('invoiceID', models.CharField(max_length=33)),
                ('cod', models.CharField(max_length=33)),
                ('returnCharge', models.CharField(max_length=33)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcel.location')),
                ('quantity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcel.quantity')),
            ],
        ),
    ]
