# Generated by Django 3.2 on 2021-04-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='location',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=models.CharField(choices=[('fragile', 'Fragile'), ('liquid', 'Liquid')], default='insideDhaka', max_length=23),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='quantity',
            field=models.CharField(choices=[('fragile', 'Fragile'), ('liquid', 'Liquid')], default='twoKG', max_length=23),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
