# Generated by Django 3.2 on 2021-04-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_auto_20210426_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=models.CharField(choices=[('insideDhaka', 'Inside of Dhaka'), ('divisionDhaka', 'Division of Dhaka'), ('outsideDhaka', 'Outside of Dhaka')], default='insideDhaka', max_length=23),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='quantity',
            field=models.CharField(choices=[('twoKG', '500 gm to 2 kg'), ('threeKG', '3 Kg'), ('fourKG', '4 Kg'), ('fiveKG', '5 Kg')], default='twoKG', max_length=23),
        ),
    ]
