# Generated by Django 3.2 on 2021-04-28 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0003_auto_20210426_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='totalPrice',
            field=models.CharField(default=django.utils.timezone.now, max_length=33),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=models.CharField(max_length=23),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='merchantName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='productType',
            field=models.CharField(max_length=23),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='quantity',
            field=models.CharField(max_length=23),
        ),
    ]
