# Generated by Django 3.2 on 2021-04-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0004_auto_20210428_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='totalPrice',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=models.CharField(choices=[('Inside of Dhaka', 'Inside of Dhaka'), ('Outside of Dhaka', 'Outside of Dhaka'), ('Division of Dhaka', 'Division of Dhaka:')], default='Inside of Dhaka', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='merchantName',
            field=models.CharField(choices=[('Style Zone', 'Style Zone')], default='Style Zone', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='productType',
            field=models.CharField(choices=[('Fragile', 'Fragile'), ('Liquid', 'Liquid')], default='Fragile', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='quantity',
            field=models.CharField(choices=[('500 gm to 2 kg', '500 gm to 2 kg'), ('3 Kg', '3 Kg'), ('4 Kg', '4 Kg'), ('5 Kg', '5 Kg')], default='500 gm to 2 kg', max_length=20),
        ),
    ]
