# Generated by Django 3.2 on 2021-04-29 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0005_auto_20210429_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='charge',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='cod',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='returnCharge',
            field=models.CharField(max_length=15),
        ),
    ]
