# Generated by Django 3.2 on 2021-04-29 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0006_auto_20210429_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='total',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
