# Generated by Django 4.2.1 on 2023-05-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=20)),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("size", models.IntegerField()),
                ("price", models.FloatField()),
            ],
        ),
    ]
