# Generated by Django 4.2.1 on 2023-05-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("YearsExperience", models.FloatField()),
                ("salary", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="House",
        ),
    ]
