# Generated by Django 3.2 on 2021-05-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Merchants',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('fra', 'Fragile'), ('liq', 'Liquid')], default='fra', max_length=10)),
                ('invoice_id', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(choices=[('in_dhaka', 'Inside of Dhaka'), ('out_dhaka', 'Outside of Dhaka'), ('div_dhaka', 'Division of Dhaka')], default='in_dhaka', max_length=30)),
                ('quantity', models.CharField(choices=[('2_kg', '500 gm to 2 Kg'), ('3_kg', '3 Kg'), ('4_kg', '4 Kg'), ('5_kg', '5 Kg')], default='2_kg', max_length=50)),
                ('cost', models.PositiveIntegerField()),
                ('order_datetime', models.DateField(auto_now_add=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_order', to='parcel.merchant')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
