# Generated by Django 4.2.6 on 2023-10-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HousingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("housing_median_age", models.IntegerField(default=0)),
                ("total_rooms", models.IntegerField(default=0)),
                ("total_bedrooms", models.FloatField(default=0.0)),
                ("population", models.IntegerField(default=0)),
                ("households", models.IntegerField(default=0)),
                ("median_income", models.FloatField(default=0.0)),
                (
                    "ocean_proximity",
                    models.CharField(
                        choices=[
                            ("NEAR BAY", "Near Bay"),
                            ("<1H OCEAN", "Less than 1 Hour to Ocean"),
                            ("INLAND", "Inland"),
                            ("NEAR OCEAN", "Near Ocean"),
                            ("ISLAND", "Island"),
                        ],
                        max_length=15,
                    ),
                ),
                ("median_house_value", models.IntegerField(default=0)),
            ],
        ),
    ]
