# Generated by Django 4.2.6 on 2023-10-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("housepriceapi", "0002_alter_housingdata_ocean_proximity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="housingdata",
            name="median_house_value",
        ),
    ]
