# Generated by Django 4.2.6 on 2023-10-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housepriceapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housingdata",
            name="ocean_proximity",
            field=models.CharField(
                choices=[
                    ("NEAR BAY", "Near Bay"),
                    ("<1H OCEAN", "Less than 1 Hour to Ocean"),
                    ("INLAND", "Inland"),
                    ("NEAR OCEAN", "Near Ocean"),
                    ("ISLAND", "Island"),
                ],
                max_length=50,
            ),
        ),
    ]
